### ISSUE TITLE
Interest in running this in Lambda?

### ISSUE THREAD

**Issue by dynamike** [chanzuckerberg/rotator#43]
I think y'all have a good start with this tool and would like to use it, but mostly inside a Lambda function. Would there be any interest here to upstream a feature to add optional Lambda functionality?

**Comment by ryanking** [comment]
@dynamike that would be great!

**Comment by dynamike** [comment]
Looking more into this having the config file abstracted into environment variables doesn't really make sense. I need to think more about this because it may make more sense to make this run via an scheduled ECS task.

**Comment by ryanking** [comment]
@dynamike that's what we do, though s/ecs/kubernetes/

**Comment by dynamike** [comment]
I'm going to close this for not and go down the ECS path a bit and will report back if there's anything meaningful to upstream.
