### ISSUE TITLE
Consider integrations with credhub and/or vault

### ISSUE THREAD

**Issue by aegershman** [chanzuckerberg/rotator#46]
So forgive me in advance, I haven't looked too deep into what work this would require / what interfaces would need to be implemented; I don't mean to sound presumptive; just putting an idea out there, etc.:

Consider integrating sinks/sources with two popular credentials managers [`credhub`](https://credhub-api.cfapps.io/version/2.5/#_generate_a_certificate_credential) and/or [`vault`](https://www.vaultproject.io/). I personally use credhub a *lot*, but hey, vault is quite popular as well.

Each of these are used by automated systems and by humans for actual generation, storage, & retrieval of creds. Being able to rotate credentials (users, certs, client creds, etc.) and sync them to either other credhub instances or other locations would be handy.

Feel free to close this whenever; again, don't mean to be presumptive, I just wanted to get the idea down in writing for consideration, even if it's either rejected, doesn't have a strong use-case, or never gets implemented, etc.

thanks for your time and thanks for your work on this project 👍

**Comment by ryanking** [comment]
@aegershman I think that is an interesting idea and I would gladly accept PRs that implement them

Given that we don't use those 2 tools currently, we're not going to be implementing them anytime soon.

**Comment by aegershman** [comment]
Gotcha, thank you for your response— right on, for now, I will close this until; I appreciate your time! 👍
